// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: pkg/api/consent/consent.proto

package consent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConsentService_RecordConsent_FullMethodName        = "/consent.ConsentService/RecordConsent"
	ConsentService_CheckConsent_FullMethodName         = "/consent.ConsentService/CheckConsent"
	ConsentService_GetUserConsents_FullMethodName      = "/consent.ConsentService/GetUserConsents"
	ConsentService_CheckPendingConsents_FullMethodName = "/consent.ConsentService/CheckPendingConsents"
	ConsentService_RevokeConsent_FullMethodName        = "/consent.ConsentService/RevokeConsent"
	ConsentService_GetConsentHistory_FullMethodName    = "/consent.ConsentService/GetConsentHistory"
	ConsentService_GetConsentStats_FullMethodName      = "/consent.ConsentService/GetConsentStats"
)

// ConsentServiceClient is the client API for ConsentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definition
type ConsentServiceClient interface {
	// Lưu đồng ý mới (single hoặc bulk)
	RecordConsent(ctx context.Context, in *RecordConsentRequest, opts ...grpc.CallOption) (*RecordConsentResponse, error)
	// Check user đã đồng ý document/version chưa
	CheckConsent(ctx context.Context, in *CheckConsentRequest, opts ...grpc.CallOption) (*CheckConsentResponse, error)
	// Lấy tất cả consents của user
	GetUserConsents(ctx context.Context, in *GetUserConsentsRequest, opts ...grpc.CallOption) (*GetUserConsentsResponse, error)
	// Check policies nào user chưa consent (pending)
	CheckPendingConsents(ctx context.Context, in *CheckPendingConsentsRequest, opts ...grpc.CallOption) (*CheckPendingConsentsResponse, error)
	// Soft delete consent (revoke)
	RevokeConsent(ctx context.Context, in *RevokeConsentRequest, opts ...grpc.CallOption) (*RevokeConsentResponse, error)
	// Phase 2: Get consent history for user+document
	GetConsentHistory(ctx context.Context, in *GetConsentHistoryRequest, opts ...grpc.CallOption) (*GetConsentHistoryResponse, error)
	// Phase 4: Get consent statistics
	GetConsentStats(ctx context.Context, in *GetConsentStatsRequest, opts ...grpc.CallOption) (*GetConsentStatsResponse, error)
}

type consentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConsentServiceClient(cc grpc.ClientConnInterface) ConsentServiceClient {
	return &consentServiceClient{cc}
}

func (c *consentServiceClient) RecordConsent(ctx context.Context, in *RecordConsentRequest, opts ...grpc.CallOption) (*RecordConsentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordConsentResponse)
	err := c.cc.Invoke(ctx, ConsentService_RecordConsent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consentServiceClient) CheckConsent(ctx context.Context, in *CheckConsentRequest, opts ...grpc.CallOption) (*CheckConsentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckConsentResponse)
	err := c.cc.Invoke(ctx, ConsentService_CheckConsent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consentServiceClient) GetUserConsents(ctx context.Context, in *GetUserConsentsRequest, opts ...grpc.CallOption) (*GetUserConsentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserConsentsResponse)
	err := c.cc.Invoke(ctx, ConsentService_GetUserConsents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consentServiceClient) CheckPendingConsents(ctx context.Context, in *CheckPendingConsentsRequest, opts ...grpc.CallOption) (*CheckPendingConsentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckPendingConsentsResponse)
	err := c.cc.Invoke(ctx, ConsentService_CheckPendingConsents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consentServiceClient) RevokeConsent(ctx context.Context, in *RevokeConsentRequest, opts ...grpc.CallOption) (*RevokeConsentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeConsentResponse)
	err := c.cc.Invoke(ctx, ConsentService_RevokeConsent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consentServiceClient) GetConsentHistory(ctx context.Context, in *GetConsentHistoryRequest, opts ...grpc.CallOption) (*GetConsentHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConsentHistoryResponse)
	err := c.cc.Invoke(ctx, ConsentService_GetConsentHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consentServiceClient) GetConsentStats(ctx context.Context, in *GetConsentStatsRequest, opts ...grpc.CallOption) (*GetConsentStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConsentStatsResponse)
	err := c.cc.Invoke(ctx, ConsentService_GetConsentStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsentServiceServer is the server API for ConsentService service.
// All implementations must embed UnimplementedConsentServiceServer
// for forward compatibility.
//
// Service definition
type ConsentServiceServer interface {
	// Lưu đồng ý mới (single hoặc bulk)
	RecordConsent(context.Context, *RecordConsentRequest) (*RecordConsentResponse, error)
	// Check user đã đồng ý document/version chưa
	CheckConsent(context.Context, *CheckConsentRequest) (*CheckConsentResponse, error)
	// Lấy tất cả consents của user
	GetUserConsents(context.Context, *GetUserConsentsRequest) (*GetUserConsentsResponse, error)
	// Check policies nào user chưa consent (pending)
	CheckPendingConsents(context.Context, *CheckPendingConsentsRequest) (*CheckPendingConsentsResponse, error)
	// Soft delete consent (revoke)
	RevokeConsent(context.Context, *RevokeConsentRequest) (*RevokeConsentResponse, error)
	// Phase 2: Get consent history for user+document
	GetConsentHistory(context.Context, *GetConsentHistoryRequest) (*GetConsentHistoryResponse, error)
	// Phase 4: Get consent statistics
	GetConsentStats(context.Context, *GetConsentStatsRequest) (*GetConsentStatsResponse, error)
	mustEmbedUnimplementedConsentServiceServer()
}

// UnimplementedConsentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConsentServiceServer struct{}

func (UnimplementedConsentServiceServer) RecordConsent(context.Context, *RecordConsentRequest) (*RecordConsentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordConsent not implemented")
}
func (UnimplementedConsentServiceServer) CheckConsent(context.Context, *CheckConsentRequest) (*CheckConsentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckConsent not implemented")
}
func (UnimplementedConsentServiceServer) GetUserConsents(context.Context, *GetUserConsentsRequest) (*GetUserConsentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserConsents not implemented")
}
func (UnimplementedConsentServiceServer) CheckPendingConsents(context.Context, *CheckPendingConsentsRequest) (*CheckPendingConsentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckPendingConsents not implemented")
}
func (UnimplementedConsentServiceServer) RevokeConsent(context.Context, *RevokeConsentRequest) (*RevokeConsentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeConsent not implemented")
}
func (UnimplementedConsentServiceServer) GetConsentHistory(context.Context, *GetConsentHistoryRequest) (*GetConsentHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConsentHistory not implemented")
}
func (UnimplementedConsentServiceServer) GetConsentStats(context.Context, *GetConsentStatsRequest) (*GetConsentStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConsentStats not implemented")
}
func (UnimplementedConsentServiceServer) mustEmbedUnimplementedConsentServiceServer() {}
func (UnimplementedConsentServiceServer) testEmbeddedByValue()                        {}

// UnsafeConsentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConsentServiceServer will
// result in compilation errors.
type UnsafeConsentServiceServer interface {
	mustEmbedUnimplementedConsentServiceServer()
}

func RegisterConsentServiceServer(s grpc.ServiceRegistrar, srv ConsentServiceServer) {
	// If the following call panics, it indicates UnimplementedConsentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConsentService_ServiceDesc, srv)
}

func _ConsentService_RecordConsent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordConsentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsentServiceServer).RecordConsent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsentService_RecordConsent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsentServiceServer).RecordConsent(ctx, req.(*RecordConsentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsentService_CheckConsent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckConsentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsentServiceServer).CheckConsent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsentService_CheckConsent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsentServiceServer).CheckConsent(ctx, req.(*CheckConsentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsentService_GetUserConsents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserConsentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsentServiceServer).GetUserConsents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsentService_GetUserConsents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsentServiceServer).GetUserConsents(ctx, req.(*GetUserConsentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsentService_CheckPendingConsents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckPendingConsentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsentServiceServer).CheckPendingConsents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsentService_CheckPendingConsents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsentServiceServer).CheckPendingConsents(ctx, req.(*CheckPendingConsentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsentService_RevokeConsent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeConsentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsentServiceServer).RevokeConsent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsentService_RevokeConsent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsentServiceServer).RevokeConsent(ctx, req.(*RevokeConsentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsentService_GetConsentHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConsentHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsentServiceServer).GetConsentHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsentService_GetConsentHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsentServiceServer).GetConsentHistory(ctx, req.(*GetConsentHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConsentService_GetConsentStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConsentStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsentServiceServer).GetConsentStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConsentService_GetConsentStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsentServiceServer).GetConsentStats(ctx, req.(*GetConsentStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConsentService_ServiceDesc is the grpc.ServiceDesc for ConsentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConsentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "consent.ConsentService",
	HandlerType: (*ConsentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecordConsent",
			Handler:    _ConsentService_RecordConsent_Handler,
		},
		{
			MethodName: "CheckConsent",
			Handler:    _ConsentService_CheckConsent_Handler,
		},
		{
			MethodName: "GetUserConsents",
			Handler:    _ConsentService_GetUserConsents_Handler,
		},
		{
			MethodName: "CheckPendingConsents",
			Handler:    _ConsentService_CheckPendingConsents_Handler,
		},
		{
			MethodName: "RevokeConsent",
			Handler:    _ConsentService_RevokeConsent_Handler,
		},
		{
			MethodName: "GetConsentHistory",
			Handler:    _ConsentService_GetConsentHistory_Handler,
		},
		{
			MethodName: "GetConsentStats",
			Handler:    _ConsentService_GetConsentStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/api/consent/consent.proto",
}
