// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: pkg/api/document/document.proto

package document

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PolicyDocument struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DocumentName       string                 `protobuf:"bytes,2,opt,name=document_name,json=documentName,proto3" json:"document_name,omitempty"`
	Platform           string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	IsMandatory        bool                   `protobuf:"varint,4,opt,name=is_mandatory,json=isMandatory,proto3" json:"is_mandatory,omitempty"`
	EffectiveTimestamp int64                  `protobuf:"varint,5,opt,name=effective_timestamp,json=effectiveTimestamp,proto3" json:"effective_timestamp,omitempty"`
	ContentHtml        string                 `protobuf:"bytes,6,opt,name=content_html,json=contentHtml,proto3" json:"content_html,omitempty"`
	FileUrl            string                 `protobuf:"bytes,7,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	CreatedAt          int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy          string                 `protobuf:"bytes,9,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PolicyDocument) Reset() {
	*x = PolicyDocument{}
	mi := &file_pkg_api_document_document_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyDocument) ProtoMessage() {}

func (x *PolicyDocument) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_document_document_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyDocument.ProtoReflect.Descriptor instead.
func (*PolicyDocument) Descriptor() ([]byte, []int) {
	return file_pkg_api_document_document_proto_rawDescGZIP(), []int{0}
}

func (x *PolicyDocument) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PolicyDocument) GetDocumentName() string {
	if x != nil {
		return x.DocumentName
	}
	return ""
}

func (x *PolicyDocument) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *PolicyDocument) GetIsMandatory() bool {
	if x != nil {
		return x.IsMandatory
	}
	return false
}

func (x *PolicyDocument) GetEffectiveTimestamp() int64 {
	if x != nil {
		return x.EffectiveTimestamp
	}
	return 0
}

func (x *PolicyDocument) GetContentHtml() string {
	if x != nil {
		return x.ContentHtml
	}
	return ""
}

func (x *PolicyDocument) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *PolicyDocument) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *PolicyDocument) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type CreateDocumentRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DocumentName       string                 `protobuf:"bytes,1,opt,name=document_name,json=documentName,proto3" json:"document_name,omitempty"`
	Platform           string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	IsMandatory        bool                   `protobuf:"varint,3,opt,name=is_mandatory,json=isMandatory,proto3" json:"is_mandatory,omitempty"`
	EffectiveTimestamp int64                  `protobuf:"varint,4,opt,name=effective_timestamp,json=effectiveTimestamp,proto3" json:"effective_timestamp,omitempty"`
	ContentHtml        string                 `protobuf:"bytes,5,opt,name=content_html,json=contentHtml,proto3" json:"content_html,omitempty"`
	FileUrl            string                 `protobuf:"bytes,6,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	CreatedBy          string                 `protobuf:"bytes,7,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateDocumentRequest) Reset() {
	*x = CreateDocumentRequest{}
	mi := &file_pkg_api_document_document_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDocumentRequest) ProtoMessage() {}

func (x *CreateDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_document_document_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDocumentRequest.ProtoReflect.Descriptor instead.
func (*CreateDocumentRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_document_document_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDocumentRequest) GetDocumentName() string {
	if x != nil {
		return x.DocumentName
	}
	return ""
}

func (x *CreateDocumentRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *CreateDocumentRequest) GetIsMandatory() bool {
	if x != nil {
		return x.IsMandatory
	}
	return false
}

func (x *CreateDocumentRequest) GetEffectiveTimestamp() int64 {
	if x != nil {
		return x.EffectiveTimestamp
	}
	return 0
}

func (x *CreateDocumentRequest) GetContentHtml() string {
	if x != nil {
		return x.ContentHtml
	}
	return ""
}

func (x *CreateDocumentRequest) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *CreateDocumentRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type CreateDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *PolicyDocument        `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDocumentResponse) Reset() {
	*x = CreateDocumentResponse{}
	mi := &file_pkg_api_document_document_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDocumentResponse) ProtoMessage() {}

func (x *CreateDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_document_document_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDocumentResponse.ProtoReflect.Descriptor instead.
func (*CreateDocumentResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_document_document_proto_rawDescGZIP(), []int{2}
}

func (x *CreateDocumentResponse) GetDocument() *PolicyDocument {
	if x != nil {
		return x.Document
	}
	return nil
}

type GetLatestPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	DocumentName  string                 `protobuf:"bytes,2,opt,name=document_name,json=documentName,proto3" json:"document_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestPolicyRequest) Reset() {
	*x = GetLatestPolicyRequest{}
	mi := &file_pkg_api_document_document_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestPolicyRequest) ProtoMessage() {}

func (x *GetLatestPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_document_document_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestPolicyRequest.ProtoReflect.Descriptor instead.
func (*GetLatestPolicyRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_document_document_proto_rawDescGZIP(), []int{3}
}

func (x *GetLatestPolicyRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *GetLatestPolicyRequest) GetDocumentName() string {
	if x != nil {
		return x.DocumentName
	}
	return ""
}

type GetLatestPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *PolicyDocument        `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestPolicyResponse) Reset() {
	*x = GetLatestPolicyResponse{}
	mi := &file_pkg_api_document_document_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestPolicyResponse) ProtoMessage() {}

func (x *GetLatestPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_document_document_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestPolicyResponse.ProtoReflect.Descriptor instead.
func (*GetLatestPolicyResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_document_document_proto_rawDescGZIP(), []int{4}
}

func (x *GetLatestPolicyResponse) GetDocument() *PolicyDocument {
	if x != nil {
		return x.Document
	}
	return nil
}

var File_pkg_api_document_document_proto protoreflect.FileDescriptor

const file_pkg_api_document_document_proto_rawDesc = "" +
	"\n" +
	"\x1fpkg/api/document/document.proto\x12\bdocument\"\xb1\x02\n" +
	"\x0ePolicyDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rdocument_name\x18\x02 \x01(\tR\fdocumentName\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12!\n" +
	"\fis_mandatory\x18\x04 \x01(\bR\visMandatory\x12/\n" +
	"\x13effective_timestamp\x18\x05 \x01(\x03R\x12effectiveTimestamp\x12!\n" +
	"\fcontent_html\x18\x06 \x01(\tR\vcontentHtml\x12\x19\n" +
	"\bfile_url\x18\a \x01(\tR\afileUrl\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\t \x01(\tR\tcreatedBy\"\x89\x02\n" +
	"\x15CreateDocumentRequest\x12#\n" +
	"\rdocument_name\x18\x01 \x01(\tR\fdocumentName\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12!\n" +
	"\fis_mandatory\x18\x03 \x01(\bR\visMandatory\x12/\n" +
	"\x13effective_timestamp\x18\x04 \x01(\x03R\x12effectiveTimestamp\x12!\n" +
	"\fcontent_html\x18\x05 \x01(\tR\vcontentHtml\x12\x19\n" +
	"\bfile_url\x18\x06 \x01(\tR\afileUrl\x12\x1d\n" +
	"\n" +
	"created_by\x18\a \x01(\tR\tcreatedBy\"N\n" +
	"\x16CreateDocumentResponse\x124\n" +
	"\bdocument\x18\x01 \x01(\v2\x18.document.PolicyDocumentR\bdocument\"Y\n" +
	"\x16GetLatestPolicyRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12#\n" +
	"\rdocument_name\x18\x02 \x01(\tR\fdocumentName\"O\n" +
	"\x17GetLatestPolicyResponse\x124\n" +
	"\bdocument\x18\x01 \x01(\v2\x18.document.PolicyDocumentR\bdocument2\xc6\x01\n" +
	"\x0fDocumentService\x12Q\n" +
	"\fCreatePolicy\x12\x1f.document.CreateDocumentRequest\x1a .document.CreateDocumentResponse\x12`\n" +
	"\x19GetLatestPolicyByPlatform\x12 .document.GetLatestPolicyRequest\x1a!.document.GetLatestPolicyResponseB=Z;github.com/thatlq1812/policy-system/shared/pkg/api/documentb\x06proto3"

var (
	file_pkg_api_document_document_proto_rawDescOnce sync.Once
	file_pkg_api_document_document_proto_rawDescData []byte
)

func file_pkg_api_document_document_proto_rawDescGZIP() []byte {
	file_pkg_api_document_document_proto_rawDescOnce.Do(func() {
		file_pkg_api_document_document_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_document_document_proto_rawDesc), len(file_pkg_api_document_document_proto_rawDesc)))
	})
	return file_pkg_api_document_document_proto_rawDescData
}

var file_pkg_api_document_document_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_api_document_document_proto_goTypes = []any{
	(*PolicyDocument)(nil),          // 0: document.PolicyDocument
	(*CreateDocumentRequest)(nil),   // 1: document.CreateDocumentRequest
	(*CreateDocumentResponse)(nil),  // 2: document.CreateDocumentResponse
	(*GetLatestPolicyRequest)(nil),  // 3: document.GetLatestPolicyRequest
	(*GetLatestPolicyResponse)(nil), // 4: document.GetLatestPolicyResponse
}
var file_pkg_api_document_document_proto_depIdxs = []int32{
	0, // 0: document.CreateDocumentResponse.document:type_name -> document.PolicyDocument
	0, // 1: document.GetLatestPolicyResponse.document:type_name -> document.PolicyDocument
	1, // 2: document.DocumentService.CreatePolicy:input_type -> document.CreateDocumentRequest
	3, // 3: document.DocumentService.GetLatestPolicyByPlatform:input_type -> document.GetLatestPolicyRequest
	2, // 4: document.DocumentService.CreatePolicy:output_type -> document.CreateDocumentResponse
	4, // 5: document.DocumentService.GetLatestPolicyByPlatform:output_type -> document.GetLatestPolicyResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_api_document_document_proto_init() }
func file_pkg_api_document_document_proto_init() {
	if File_pkg_api_document_document_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_document_document_proto_rawDesc), len(file_pkg_api_document_document_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_document_document_proto_goTypes,
		DependencyIndexes: file_pkg_api_document_document_proto_depIdxs,
		MessageInfos:      file_pkg_api_document_document_proto_msgTypes,
	}.Build()
	File_pkg_api_document_document_proto = out.File
	file_pkg_api_document_document_proto_goTypes = nil
	file_pkg_api_document_document_proto_depIdxs = nil
}
