// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: pkg/api/consent/consent.proto

package consent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Messages
type Consent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Platform         string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	DocumentId       string                 `protobuf:"bytes,4,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	DocumentName     string                 `protobuf:"bytes,5,opt,name=document_name,json=documentName,proto3" json:"document_name,omitempty"`
	VersionTimestamp int64                  `protobuf:"varint,6,opt,name=version_timestamp,json=versionTimestamp,proto3" json:"version_timestamp,omitempty"`
	AgreedAt         int64                  `protobuf:"varint,7,opt,name=agreed_at,json=agreedAt,proto3" json:"agreed_at,omitempty"` // Unix timestamp
	AgreedFileUrl    string                 `protobuf:"bytes,8,opt,name=agreed_file_url,json=agreedFileUrl,proto3" json:"agreed_file_url,omitempty"`
	ConsentMethod    string                 `protobuf:"bytes,9,opt,name=consent_method,json=consentMethod,proto3" json:"consent_method,omitempty"`
	IpAddress        string                 `protobuf:"bytes,10,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	UserAgent        string                 `protobuf:"bytes,11,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	IsDeleted        bool                   `protobuf:"varint,12,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	DeletedAt        int64                  `protobuf:"varint,13,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	CreatedAt        int64                  `protobuf:"varint,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        int64                  `protobuf:"varint,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Consent) Reset() {
	*x = Consent{}
	mi := &file_pkg_api_consent_consent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Consent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Consent) ProtoMessage() {}

func (x *Consent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_consent_consent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Consent.ProtoReflect.Descriptor instead.
func (*Consent) Descriptor() ([]byte, []int) {
	return file_pkg_api_consent_consent_proto_rawDescGZIP(), []int{0}
}

func (x *Consent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Consent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Consent) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *Consent) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *Consent) GetDocumentName() string {
	if x != nil {
		return x.DocumentName
	}
	return ""
}

func (x *Consent) GetVersionTimestamp() int64 {
	if x != nil {
		return x.VersionTimestamp
	}
	return 0
}

func (x *Consent) GetAgreedAt() int64 {
	if x != nil {
		return x.AgreedAt
	}
	return 0
}

func (x *Consent) GetAgreedFileUrl() string {
	if x != nil {
		return x.AgreedFileUrl
	}
	return ""
}

func (x *Consent) GetConsentMethod() string {
	if x != nil {
		return x.ConsentMethod
	}
	return ""
}

func (x *Consent) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *Consent) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *Consent) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *Consent) GetDeletedAt() int64 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

func (x *Consent) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Consent) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type ConsentInput struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DocumentId       string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	DocumentName     string                 `protobuf:"bytes,2,opt,name=document_name,json=documentName,proto3" json:"document_name,omitempty"`
	VersionTimestamp int64                  `protobuf:"varint,3,opt,name=version_timestamp,json=versionTimestamp,proto3" json:"version_timestamp,omitempty"`
	AgreedFileUrl    string                 `protobuf:"bytes,4,opt,name=agreed_file_url,json=agreedFileUrl,proto3" json:"agreed_file_url,omitempty"` // Optional
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConsentInput) Reset() {
	*x = ConsentInput{}
	mi := &file_pkg_api_consent_consent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsentInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsentInput) ProtoMessage() {}

func (x *ConsentInput) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_consent_consent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsentInput.ProtoReflect.Descriptor instead.
func (*ConsentInput) Descriptor() ([]byte, []int) {
	return file_pkg_api_consent_consent_proto_rawDescGZIP(), []int{1}
}

func (x *ConsentInput) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *ConsentInput) GetDocumentName() string {
	if x != nil {
		return x.DocumentName
	}
	return ""
}

func (x *ConsentInput) GetVersionTimestamp() int64 {
	if x != nil {
		return x.VersionTimestamp
	}
	return 0
}

func (x *ConsentInput) GetAgreedFileUrl() string {
	if x != nil {
		return x.AgreedFileUrl
	}
	return ""
}

// RecordConsent - Lưu đồng ý mới
type RecordConsentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	Consents      []*ConsentInput        `protobuf:"bytes,3,rep,name=consents,proto3" json:"consents,omitempty"`                                // Bulk consent
	ConsentMethod string                 `protobuf:"bytes,4,opt,name=consent_method,json=consentMethod,proto3" json:"consent_method,omitempty"` // 'REGISTRATION', 'UI', 'API'
	IpAddress     string                 `protobuf:"bytes,5,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`             // Optional
	UserAgent     string                 `protobuf:"bytes,6,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`             // Optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordConsentRequest) Reset() {
	*x = RecordConsentRequest{}
	mi := &file_pkg_api_consent_consent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordConsentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordConsentRequest) ProtoMessage() {}

func (x *RecordConsentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_consent_consent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordConsentRequest.ProtoReflect.Descriptor instead.
func (*RecordConsentRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_consent_consent_proto_rawDescGZIP(), []int{2}
}

func (x *RecordConsentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RecordConsentRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *RecordConsentRequest) GetConsents() []*ConsentInput {
	if x != nil {
		return x.Consents
	}
	return nil
}

func (x *RecordConsentRequest) GetConsentMethod() string {
	if x != nil {
		return x.ConsentMethod
	}
	return ""
}

func (x *RecordConsentRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *RecordConsentRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

type RecordConsentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Consents      []*Consent             `protobuf:"bytes,1,rep,name=consents,proto3" json:"consents,omitempty"`
	TotalRecorded int32                  `protobuf:"varint,2,opt,name=total_recorded,json=totalRecorded,proto3" json:"total_recorded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordConsentResponse) Reset() {
	*x = RecordConsentResponse{}
	mi := &file_pkg_api_consent_consent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordConsentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordConsentResponse) ProtoMessage() {}

func (x *RecordConsentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_consent_consent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordConsentResponse.ProtoReflect.Descriptor instead.
func (*RecordConsentResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_consent_consent_proto_rawDescGZIP(), []int{3}
}

func (x *RecordConsentResponse) GetConsents() []*Consent {
	if x != nil {
		return x.Consents
	}
	return nil
}

func (x *RecordConsentResponse) GetTotalRecorded() int32 {
	if x != nil {
		return x.TotalRecorded
	}
	return 0
}

// CheckConsent - Check user đã consent chưa
type CheckConsentRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UserId              string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DocumentId          string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	MinVersionTimestamp int64                  `protobuf:"varint,3,opt,name=min_version_timestamp,json=minVersionTimestamp,proto3" json:"min_version_timestamp,omitempty"` // Check >= version này
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CheckConsentRequest) Reset() {
	*x = CheckConsentRequest{}
	mi := &file_pkg_api_consent_consent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckConsentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckConsentRequest) ProtoMessage() {}

func (x *CheckConsentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_consent_consent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckConsentRequest.ProtoReflect.Descriptor instead.
func (*CheckConsentRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_consent_consent_proto_rawDescGZIP(), []int{4}
}

func (x *CheckConsentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckConsentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *CheckConsentRequest) GetMinVersionTimestamp() int64 {
	if x != nil {
		return x.MinVersionTimestamp
	}
	return 0
}

type CheckConsentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasConsented  bool                   `protobuf:"varint,1,opt,name=has_consented,json=hasConsented,proto3" json:"has_consented,omitempty"`
	LatestConsent *Consent               `protobuf:"bytes,2,opt,name=latest_consent,json=latestConsent,proto3" json:"latest_consent,omitempty"` // null nếu chưa consent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckConsentResponse) Reset() {
	*x = CheckConsentResponse{}
	mi := &file_pkg_api_consent_consent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckConsentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckConsentResponse) ProtoMessage() {}

func (x *CheckConsentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_consent_consent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckConsentResponse.ProtoReflect.Descriptor instead.
func (*CheckConsentResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_consent_consent_proto_rawDescGZIP(), []int{5}
}

func (x *CheckConsentResponse) GetHasConsented() bool {
	if x != nil {
		return x.HasConsented
	}
	return false
}

func (x *CheckConsentResponse) GetLatestConsent() *Consent {
	if x != nil {
		return x.LatestConsent
	}
	return nil
}

// GetUserConsents - Lấy tất cả consents của user
type GetUserConsentsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IncludeDeleted bool                   `protobuf:"varint,2,opt,name=include_deleted,json=includeDeleted,proto3" json:"include_deleted,omitempty"` // Default false
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetUserConsentsRequest) Reset() {
	*x = GetUserConsentsRequest{}
	mi := &file_pkg_api_consent_consent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserConsentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserConsentsRequest) ProtoMessage() {}

func (x *GetUserConsentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_consent_consent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserConsentsRequest.ProtoReflect.Descriptor instead.
func (*GetUserConsentsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_consent_consent_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserConsentsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserConsentsRequest) GetIncludeDeleted() bool {
	if x != nil {
		return x.IncludeDeleted
	}
	return false
}

type GetUserConsentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Consents      []*Consent             `protobuf:"bytes,1,rep,name=consents,proto3" json:"consents,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserConsentsResponse) Reset() {
	*x = GetUserConsentsResponse{}
	mi := &file_pkg_api_consent_consent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserConsentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserConsentsResponse) ProtoMessage() {}

func (x *GetUserConsentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_consent_consent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserConsentsResponse.ProtoReflect.Descriptor instead.
func (*GetUserConsentsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_consent_consent_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserConsentsResponse) GetConsents() []*Consent {
	if x != nil {
		return x.Consents
	}
	return nil
}

func (x *GetUserConsentsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// CheckPendingConsents - Check policies nào chưa consent
type PendingPolicy struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DocumentId       string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	DocumentName     string                 `protobuf:"bytes,2,opt,name=document_name,json=documentName,proto3" json:"document_name,omitempty"`
	VersionTimestamp int64                  `protobuf:"varint,3,opt,name=version_timestamp,json=versionTimestamp,proto3" json:"version_timestamp,omitempty"`
	Platform         string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PendingPolicy) Reset() {
	*x = PendingPolicy{}
	mi := &file_pkg_api_consent_consent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingPolicy) ProtoMessage() {}

func (x *PendingPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_consent_consent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingPolicy.ProtoReflect.Descriptor instead.
func (*PendingPolicy) Descriptor() ([]byte, []int) {
	return file_pkg_api_consent_consent_proto_rawDescGZIP(), []int{8}
}

func (x *PendingPolicy) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *PendingPolicy) GetDocumentName() string {
	if x != nil {
		return x.DocumentName
	}
	return ""
}

func (x *PendingPolicy) GetVersionTimestamp() int64 {
	if x != nil {
		return x.VersionTimestamp
	}
	return 0
}

func (x *PendingPolicy) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type CheckPendingConsentsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Platform       string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	LatestPolicies []*PendingPolicy       `protobuf:"bytes,3,rep,name=latest_policies,json=latestPolicies,proto3" json:"latest_policies,omitempty"` // Gateway truyền vào
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckPendingConsentsRequest) Reset() {
	*x = CheckPendingConsentsRequest{}
	mi := &file_pkg_api_consent_consent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPendingConsentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPendingConsentsRequest) ProtoMessage() {}

func (x *CheckPendingConsentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_consent_consent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPendingConsentsRequest.ProtoReflect.Descriptor instead.
func (*CheckPendingConsentsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_consent_consent_proto_rawDescGZIP(), []int{9}
}

func (x *CheckPendingConsentsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckPendingConsentsRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *CheckPendingConsentsRequest) GetLatestPolicies() []*PendingPolicy {
	if x != nil {
		return x.LatestPolicies
	}
	return nil
}

type CheckPendingConsentsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PendingPolicies []*PendingPolicy       `protobuf:"bytes,1,rep,name=pending_policies,json=pendingPolicies,proto3" json:"pending_policies,omitempty"`
	RequiresConsent bool                   `protobuf:"varint,2,opt,name=requires_consent,json=requiresConsent,proto3" json:"requires_consent,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheckPendingConsentsResponse) Reset() {
	*x = CheckPendingConsentsResponse{}
	mi := &file_pkg_api_consent_consent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPendingConsentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPendingConsentsResponse) ProtoMessage() {}

func (x *CheckPendingConsentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_consent_consent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPendingConsentsResponse.ProtoReflect.Descriptor instead.
func (*CheckPendingConsentsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_consent_consent_proto_rawDescGZIP(), []int{10}
}

func (x *CheckPendingConsentsResponse) GetPendingPolicies() []*PendingPolicy {
	if x != nil {
		return x.PendingPolicies
	}
	return nil
}

func (x *CheckPendingConsentsResponse) GetRequiresConsent() bool {
	if x != nil {
		return x.RequiresConsent
	}
	return false
}

// RevokeConsent - Soft delete consent
type RevokeConsentRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DocumentId       string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	VersionTimestamp int64                  `protobuf:"varint,3,opt,name=version_timestamp,json=versionTimestamp,proto3" json:"version_timestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RevokeConsentRequest) Reset() {
	*x = RevokeConsentRequest{}
	mi := &file_pkg_api_consent_consent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeConsentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeConsentRequest) ProtoMessage() {}

func (x *RevokeConsentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_consent_consent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeConsentRequest.ProtoReflect.Descriptor instead.
func (*RevokeConsentRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_consent_consent_proto_rawDescGZIP(), []int{11}
}

func (x *RevokeConsentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RevokeConsentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *RevokeConsentRequest) GetVersionTimestamp() int64 {
	if x != nil {
		return x.VersionTimestamp
	}
	return 0
}

type RevokeConsentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeConsentResponse) Reset() {
	*x = RevokeConsentResponse{}
	mi := &file_pkg_api_consent_consent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeConsentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeConsentResponse) ProtoMessage() {}

func (x *RevokeConsentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_consent_consent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeConsentResponse.ProtoReflect.Descriptor instead.
func (*RevokeConsentResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_consent_consent_proto_rawDescGZIP(), []int{12}
}

func (x *RevokeConsentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RevokeConsentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_api_consent_consent_proto protoreflect.FileDescriptor

const file_pkg_api_consent_consent_proto_rawDesc = "" +
	"\n" +
	"\x1dpkg/api/consent/consent.proto\x12\aconsent\"\xe7\x03\n" +
	"\aConsent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x1f\n" +
	"\vdocument_id\x18\x04 \x01(\tR\n" +
	"documentId\x12#\n" +
	"\rdocument_name\x18\x05 \x01(\tR\fdocumentName\x12+\n" +
	"\x11version_timestamp\x18\x06 \x01(\x03R\x10versionTimestamp\x12\x1b\n" +
	"\tagreed_at\x18\a \x01(\x03R\bagreedAt\x12&\n" +
	"\x0fagreed_file_url\x18\b \x01(\tR\ragreedFileUrl\x12%\n" +
	"\x0econsent_method\x18\t \x01(\tR\rconsentMethod\x12\x1d\n" +
	"\n" +
	"ip_address\x18\n" +
	" \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\v \x01(\tR\tuserAgent\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\f \x01(\bR\tisDeleted\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\r \x01(\x03R\tdeletedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\x03R\tupdatedAt\"\xa9\x01\n" +
	"\fConsentInput\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12#\n" +
	"\rdocument_name\x18\x02 \x01(\tR\fdocumentName\x12+\n" +
	"\x11version_timestamp\x18\x03 \x01(\x03R\x10versionTimestamp\x12&\n" +
	"\x0fagreed_file_url\x18\x04 \x01(\tR\ragreedFileUrl\"\xe3\x01\n" +
	"\x14RecordConsentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x121\n" +
	"\bconsents\x18\x03 \x03(\v2\x15.consent.ConsentInputR\bconsents\x12%\n" +
	"\x0econsent_method\x18\x04 \x01(\tR\rconsentMethod\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x05 \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x06 \x01(\tR\tuserAgent\"l\n" +
	"\x15RecordConsentResponse\x12,\n" +
	"\bconsents\x18\x01 \x03(\v2\x10.consent.ConsentR\bconsents\x12%\n" +
	"\x0etotal_recorded\x18\x02 \x01(\x05R\rtotalRecorded\"\x83\x01\n" +
	"\x13CheckConsentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x122\n" +
	"\x15min_version_timestamp\x18\x03 \x01(\x03R\x13minVersionTimestamp\"t\n" +
	"\x14CheckConsentResponse\x12#\n" +
	"\rhas_consented\x18\x01 \x01(\bR\fhasConsented\x127\n" +
	"\x0elatest_consent\x18\x02 \x01(\v2\x10.consent.ConsentR\rlatestConsent\"Z\n" +
	"\x16GetUserConsentsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0finclude_deleted\x18\x02 \x01(\bR\x0eincludeDeleted\"]\n" +
	"\x17GetUserConsentsResponse\x12,\n" +
	"\bconsents\x18\x01 \x03(\v2\x10.consent.ConsentR\bconsents\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x9e\x01\n" +
	"\rPendingPolicy\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12#\n" +
	"\rdocument_name\x18\x02 \x01(\tR\fdocumentName\x12+\n" +
	"\x11version_timestamp\x18\x03 \x01(\x03R\x10versionTimestamp\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\"\x93\x01\n" +
	"\x1bCheckPendingConsentsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12?\n" +
	"\x0flatest_policies\x18\x03 \x03(\v2\x16.consent.PendingPolicyR\x0elatestPolicies\"\x8c\x01\n" +
	"\x1cCheckPendingConsentsResponse\x12A\n" +
	"\x10pending_policies\x18\x01 \x03(\v2\x16.consent.PendingPolicyR\x0fpendingPolicies\x12)\n" +
	"\x10requires_consent\x18\x02 \x01(\bR\x0frequiresConsent\"}\n" +
	"\x14RevokeConsentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12+\n" +
	"\x11version_timestamp\x18\x03 \x01(\x03R\x10versionTimestamp\"K\n" +
	"\x15RevokeConsentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xb8\x03\n" +
	"\x0eConsentService\x12N\n" +
	"\rRecordConsent\x12\x1d.consent.RecordConsentRequest\x1a\x1e.consent.RecordConsentResponse\x12K\n" +
	"\fCheckConsent\x12\x1c.consent.CheckConsentRequest\x1a\x1d.consent.CheckConsentResponse\x12T\n" +
	"\x0fGetUserConsents\x12\x1f.consent.GetUserConsentsRequest\x1a .consent.GetUserConsentsResponse\x12c\n" +
	"\x14CheckPendingConsents\x12$.consent.CheckPendingConsentsRequest\x1a%.consent.CheckPendingConsentsResponse\x12N\n" +
	"\rRevokeConsent\x12\x1d.consent.RevokeConsentRequest\x1a\x1e.consent.RevokeConsentResponseB<Z:github.com/thatlq1812/policy-system/shared/pkg/api/consentb\x06proto3"

var (
	file_pkg_api_consent_consent_proto_rawDescOnce sync.Once
	file_pkg_api_consent_consent_proto_rawDescData []byte
)

func file_pkg_api_consent_consent_proto_rawDescGZIP() []byte {
	file_pkg_api_consent_consent_proto_rawDescOnce.Do(func() {
		file_pkg_api_consent_consent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_consent_consent_proto_rawDesc), len(file_pkg_api_consent_consent_proto_rawDesc)))
	})
	return file_pkg_api_consent_consent_proto_rawDescData
}

var file_pkg_api_consent_consent_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_pkg_api_consent_consent_proto_goTypes = []any{
	(*Consent)(nil),                      // 0: consent.Consent
	(*ConsentInput)(nil),                 // 1: consent.ConsentInput
	(*RecordConsentRequest)(nil),         // 2: consent.RecordConsentRequest
	(*RecordConsentResponse)(nil),        // 3: consent.RecordConsentResponse
	(*CheckConsentRequest)(nil),          // 4: consent.CheckConsentRequest
	(*CheckConsentResponse)(nil),         // 5: consent.CheckConsentResponse
	(*GetUserConsentsRequest)(nil),       // 6: consent.GetUserConsentsRequest
	(*GetUserConsentsResponse)(nil),      // 7: consent.GetUserConsentsResponse
	(*PendingPolicy)(nil),                // 8: consent.PendingPolicy
	(*CheckPendingConsentsRequest)(nil),  // 9: consent.CheckPendingConsentsRequest
	(*CheckPendingConsentsResponse)(nil), // 10: consent.CheckPendingConsentsResponse
	(*RevokeConsentRequest)(nil),         // 11: consent.RevokeConsentRequest
	(*RevokeConsentResponse)(nil),        // 12: consent.RevokeConsentResponse
}
var file_pkg_api_consent_consent_proto_depIdxs = []int32{
	1,  // 0: consent.RecordConsentRequest.consents:type_name -> consent.ConsentInput
	0,  // 1: consent.RecordConsentResponse.consents:type_name -> consent.Consent
	0,  // 2: consent.CheckConsentResponse.latest_consent:type_name -> consent.Consent
	0,  // 3: consent.GetUserConsentsResponse.consents:type_name -> consent.Consent
	8,  // 4: consent.CheckPendingConsentsRequest.latest_policies:type_name -> consent.PendingPolicy
	8,  // 5: consent.CheckPendingConsentsResponse.pending_policies:type_name -> consent.PendingPolicy
	2,  // 6: consent.ConsentService.RecordConsent:input_type -> consent.RecordConsentRequest
	4,  // 7: consent.ConsentService.CheckConsent:input_type -> consent.CheckConsentRequest
	6,  // 8: consent.ConsentService.GetUserConsents:input_type -> consent.GetUserConsentsRequest
	9,  // 9: consent.ConsentService.CheckPendingConsents:input_type -> consent.CheckPendingConsentsRequest
	11, // 10: consent.ConsentService.RevokeConsent:input_type -> consent.RevokeConsentRequest
	3,  // 11: consent.ConsentService.RecordConsent:output_type -> consent.RecordConsentResponse
	5,  // 12: consent.ConsentService.CheckConsent:output_type -> consent.CheckConsentResponse
	7,  // 13: consent.ConsentService.GetUserConsents:output_type -> consent.GetUserConsentsResponse
	10, // 14: consent.ConsentService.CheckPendingConsents:output_type -> consent.CheckPendingConsentsResponse
	12, // 15: consent.ConsentService.RevokeConsent:output_type -> consent.RevokeConsentResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_api_consent_consent_proto_init() }
func file_pkg_api_consent_consent_proto_init() {
	if File_pkg_api_consent_consent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_consent_consent_proto_rawDesc), len(file_pkg_api_consent_consent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_consent_consent_proto_goTypes,
		DependencyIndexes: file_pkg_api_consent_consent_proto_depIdxs,
		MessageInfos:      file_pkg_api_consent_consent_proto_msgTypes,
	}.Build()
	File_pkg_api_consent_consent_proto = out.File
	file_pkg_api_consent_consent_proto_goTypes = nil
	file_pkg_api_consent_consent_proto_depIdxs = nil
}
